### PR TITLE
Add repository URL to Cargo.toml

### PR DESCRIPTION
**Pull request by jayvdb**

### CODE REVIEW

**Comment by ChristianMurphy** [comment]
Hey @jayvdb!
Thanks for opening a PR.

This project isn't actively maintained anymore.
https://github.com/wooorm/mdxjs-rs is its replacement.

It would be nice if the projects could merge together again, see https://github.com/mdx-js/rust/issues/2, but that hasn't gotten any traction yet.

**Comment by jayvdb** [comment]
thanks for the pointers.
still it would be useful to have the crate metadata accurate, which will help people find the repo , and then you can put a note in the README about the project status.

**Comment by ChristianMurphy** [comment]
> still it would be useful to have the crate metadata accurate

I agree, again see #2, there are currently no active maintainers with publish access to cargo.
Without that, this update and updating the readme would have no impact on anyone looking at cargo.

If active maintainers did have access, this project would likely merge with https://github.com/wooorm/mdxjs-rs, which does have accurate cargo metadata.

**Comment by wooorm** [comment]
Closing, I’ll clean/archive this repo soon. Hoping that #2 can pass before that.

**Pull request closed without merging**
